# Generated by Django 4.1.1 on 2022-09-22 21:00

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PureWindowsPath('C:/Users/Lucas/Desktop/Programming/PostAutomator - Copia/PostAutomate/media')),
        ),
    ]
